import { BotIcon, User2Icon } from "lucide-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { ThemeProvider } from "next-themes";
import "./globals.css";

import { SiX } from "@icons-pack/react-simple-icons";

import { Button } from "@/_components/ui/button";
import SwitchingTheme from "@/_components/app/switchingTheme";
import Tracking from "@/_components/app/tracking";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="m-auto max-w-3xl">
            <header className="p-8 font-mono">
              <div className="grid grid-flow-col grid-cols-[auto_1fr]">
                <div>
                  <Link href="/">
                    <BotIcon size={32} />
                  </Link>
                </div>
                <div className="grid grid-flow-col items-center justify-end gap-4">
                  <div>
                    <Link href="/examples">Studio</Link>
                  </div>
                  <SwitchingTheme />
                </div>
              </div>
            </header>
            <div className="min-h-lvh p-8 font-mono">{children}</div>
            <footer className="p-8 font-mono text-xs">
              <div className="grid grid-flow-col grid-cols-[auto_1fr]">
                <div className="grid grid-flow-col gap-4">
                  <div>
                    <Link href="#">Privacy Policy</Link>
                  </div>
                  <div>
                    <Link href="#">Terms of Service</Link>
                  </div>
                </div>
                <div className="grid grid-flow-col justify-end gap-4">
                  <div>
                    <Link href="#">
                      <SiX size={12} />
                    </Link>
                  </div>
                </div>
              </div>
            </footer>
          </div>
          <Tracking gaId={process.env.NEXT_PUBLIC_GA_ID} />
        </ThemeProvider>
      </body>
    </html>
  );
}
